export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as ProjectsPage } from './ProjectsPage'
export { default as ErrorPage } from './ErrorPage'
export { default as Layout } from './Layout'