export { default as Navbar } from './Navbar'
export { default as HeroSection } from './HeroSection'
export { default as AboutSection } from './AboutSection'
export { default as Footer } from './Footer'
export { default as SkillsSection} from './SkillsSection'
export { default as ProjectSection } from './ProjectsSection'